<a href="https://colab.research.google.com/github/anushkaghule25-design/data_science_lab/blob/main/InverseMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 matrix
B = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 0]
])

# Find inverse
B_inverse = np.linalg.inv(B)

print("Matrix B:")
print(B)
print("Inverse of B:")
print(B_inverse)


Matrix B:
[[2 1 1]
 [1 3 2]
 [1 0 0]]
Inverse of B:
[[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]
