<a href="https://colab.research.google.com/github/anushkaghule25-design/data_science_lab/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Find determinant
det_A = np.linalg.det(A)

print("Matrix A:")
print(A)
print("Determinant of A:", det_A)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of A: 0.0
